package vista;

/**
 * Clase donde muestra la pantalla Principal del programa
 *
 * @author IvanSM
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Banner = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        FondoyBoton = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        fondoVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(119, 30, 52));
        setMaximumSize(new java.awt.Dimension(900, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Banner.setBackground(new java.awt.Color(119, 30, 52));
        Banner.setForeground(new java.awt.Color(119, 30, 52));
        Banner.setLayout(new javax.swing.BoxLayout(Banner, javax.swing.BoxLayout.LINE_AXIS));

        lblBienvenido.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("Bienvenido al mejor circo");
        lblBienvenido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Banner.add(lblBienvenido);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.weightx = 0.6;
        getContentPane().add(Banner, gridBagConstraints);

        FondoyBoton.setBackground(new java.awt.Color(255, 255, 255));
        FondoyBoton.setOpaque(false);
        FondoyBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        FondoyBoton.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 150, 60));

        fondoVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoVentana.setIcon(new javax.swing.ImageIcon("C:\\Users\\IvanSM\\Documents\\NetBeansProjects\\ProjectoCircoIvanSM\\src\\images\\circo.gif")); // NOI18N
        fondoVentana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FondoyBoton.add(fondoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(FondoyBoton, gridBagConstraints);

        setSize(new java.awt.Dimension(840, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton Iniciar, el evento. crea y lanza la ventana secundaria y
     * la hace visible.
     *
     * @param evt
     */
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        VentanaSecundaria vSecundaria = new VentanaSecundaria();
        vSecundaria.setVisible(true);
        this.setVisible(false);// Cierra la ventana principal y deja la secundaria
    }//GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JPanel FondoyBoton;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JLabel lblBienvenido;
    // End of variables declaration//GEN-END:variables
}
