package vista;

/**
 * Clase ventana donde esta el formulario para insertar Animales en la BD
 *
 * @author IvanSM
 */
public class VentanaAnimales extends javax.swing.JFrame {

    /**
     * Creates new form VistaAnimales
     */
    public VentanaAnimales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        formularioAnimales = new javax.swing.JPanel();
        nombreAnimal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        tipoAnimal = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        aniosAnimal = new javax.swing.JLabel();
        txtAnios = new javax.swing.JTextField();
        pesoAnimal = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        estaturaAnimal = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        nombreAtraccionAnimal = new javax.swing.JLabel();
        listNombreAtraccion = new javax.swing.JComboBox<>();
        nombrePistaAnimal = new javax.swing.JLabel();
        listNombrePista = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        tituloAnimal = new javax.swing.JLabel();
        fondoVentana = new javax.swing.JLabel();

        setResizable(false);

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setOpaque(false);
        panelFormulario.setLayout(new javax.swing.BoxLayout(panelFormulario, javax.swing.BoxLayout.LINE_AXIS));

        formularioAnimales.setBackground(new java.awt.Color(0, 0, 0, 150));
        formularioAnimales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombreAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreAnimal.setText("Nombre:");
        nombreAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombreAnimal.setPreferredSize(new java.awt.Dimension(90, 24));
        nombreAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        formularioAnimales.add(nombreAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 48));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        formularioAnimales.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 270, 30));

        tipoAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tipoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tipoAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipoAnimal.setText("Tipo: ");
        formularioAnimales.add(tipoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 48));

        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        formularioAnimales.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 30));

        aniosAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        aniosAnimal.setForeground(new java.awt.Color(255, 255, 255));
        aniosAnimal.setText("Años:");
        formularioAnimales.add(aniosAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 48));

        txtAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniosActionPerformed(evt);
            }
        });
        formularioAnimales.add(txtAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));

        pesoAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pesoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        pesoAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pesoAnimal.setText("Peso:");
        formularioAnimales.add(pesoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 48));
        formularioAnimales.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 30));

        estaturaAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estaturaAnimal.setForeground(new java.awt.Color(255, 255, 255));
        estaturaAnimal.setText("Estatura:");
        formularioAnimales.add(estaturaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 90, 30));
        formularioAnimales.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 80, 30));

        nombreAtraccionAnimal.setBackground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreAtraccionAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setText("Nombre de atracción:");
        formularioAnimales.add(nombreAtraccionAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 329, 48));

        listNombreAtraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El gran carnívoro", "El gran felino", "El orangután", "La espectacular", "Las jirafas" }));
        formularioAnimales.add(listNombreAtraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 48));

        nombrePistaAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombrePistaAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombrePistaAnimal.setText("Nombre de la pista:");
        formularioAnimales.add(nombrePistaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 170, 48));

        listNombrePista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La grande", "LATERAL1", "LATERAL2", "SUPER" }));
        formularioAnimales.add(listNombrePista, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 160, 48));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        formularioAnimales.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        formularioAnimales.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        formularioAnimales.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 80, 40));

        panelFormulario.add(formularioAnimales);

        tituloAnimal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tituloAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tituloAnimal.setText("Insertar animal en la base de datos");

        fondoVentana.setIcon(new javax.swing.ImageIcon("C:\\Users\\IvanSM\\Documents\\NetBeansProjects\\ProjectoCircoIvanSM\\src\\images\\mono.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(842, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniosActionPerformed

    }//GEN-LAST:event_txtAniosActionPerformed

    /**
     * Evento del boton Atras que cierra la ventana animales.
     *
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);// Cierra la ventana principal y deja la secundaria
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * Evento del boton Guardad el evento se hace en CtrlAnimales, ya que
     * necesita conexion con la bd.
     *
     * @param evt
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Evento del boton limpiar que hace limpiar los campos del formulario.
     *
     * @param evt
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.txtNombre.setText(null);
        this.txtTipo.setText(null);
        this.txtAnios.setText(null);
        this.txtEstatura.setText(null);
        this.txtPeso.setText(null);

    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aniosAnimal;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel estaturaAnimal;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JPanel formularioAnimales;
    public javax.swing.JComboBox<String> listNombreAtraccion;
    public javax.swing.JComboBox<String> listNombrePista;
    private javax.swing.JLabel nombreAnimal;
    private javax.swing.JLabel nombreAtraccionAnimal;
    private javax.swing.JLabel nombrePistaAnimal;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel pesoAnimal;
    private javax.swing.JLabel tipoAnimal;
    private javax.swing.JLabel tituloAnimal;
    public javax.swing.JTextField txtAnios;
    public javax.swing.JTextField txtEstatura;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
