package vista;

/**
 * Clase donde podemos consultar los datos de un Animal de la BD.
 *
 * @author IvanSM
 */
public class VentanaDatosAnimal extends javax.swing.JFrame {

    /**
     * Creates new form VistaAnimales
     */
    public VentanaDatosAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreAnimal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        tipoAnimal = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        aniosAnimal = new javax.swing.JLabel();
        txtAnios = new javax.swing.JTextField();
        pesoAnimal = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        estaturaAnimal = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        nombreAtraccionAnimal = new javax.swing.JLabel();
        txtNombreAtraccion = new javax.swing.JTextField();
        nombrePistaAnimal = new javax.swing.JLabel();
        txtNombrePista = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        tituloAnimal = new javax.swing.JLabel();
        fondoVentana = new javax.swing.JLabel();

        setResizable(false);

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setOpaque(false);
        panelFormulario.setLayout(new javax.swing.BoxLayout(panelFormulario, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombreAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreAnimal.setText("Nombre:");
        nombreAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombreAnimal.setPreferredSize(new java.awt.Dimension(90, 24));
        nombreAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(nombreAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 48));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 270, 30));

        tipoAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tipoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tipoAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipoAnimal.setText("Tipo: ");
        jPanel1.add(tipoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 48));

        txtTipo.setEditable(false);
        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 30));

        aniosAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        aniosAnimal.setForeground(new java.awt.Color(255, 255, 255));
        aniosAnimal.setText("Años:");
        jPanel1.add(aniosAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 48));

        txtAnios.setEditable(false);
        txtAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniosActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));

        pesoAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pesoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        pesoAnimal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pesoAnimal.setText("Peso:");
        jPanel1.add(pesoAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 48));

        txtPeso.setEditable(false);
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 30));

        estaturaAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estaturaAnimal.setForeground(new java.awt.Color(255, 255, 255));
        estaturaAnimal.setText("Estatura:");
        jPanel1.add(estaturaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 90, 30));

        txtEstatura.setEditable(false);
        jPanel1.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 80, 30));

        nombreAtraccionAnimal.setBackground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreAtraccionAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setText("Nombre de atracción:");
        jPanel1.add(nombreAtraccionAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 329, 48));

        txtNombreAtraccion.setEditable(false);
        jPanel1.add(txtNombreAtraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        nombrePistaAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombrePistaAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombrePistaAnimal.setText("Nombre de la pista:");
        jPanel1.add(nombrePistaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 170, 48));

        txtNombrePista.setEditable(false);
        jPanel1.add(txtNombrePista, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 160, 30));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 80, 40));

        panelFormulario.add(jPanel1);

        tituloAnimal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tituloAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tituloAnimal.setText("Insertar animal en la base de datos");

        fondoVentana.setIcon(new javax.swing.ImageIcon("C:\\Users\\IvanSM\\Documents\\NetBeansProjects\\ProjectoCircoIvanSM\\src\\images\\mono.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(842, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniosActionPerformed

    }//GEN-LAST:event_txtAniosActionPerformed

    /**
     * Evento del boton Atras que cierra la ventana animales.
     *
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);// Cierra la ventana principal y deja la secundaria
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * Evento del boton limpiar que hace limpiar los campos del formulario.
     *
     * @param evt
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.txtNombre.setText(null);
        this.txtTipo.setText(null);
        this.txtAnios.setText(null);
        this.txtEstatura.setText(null);
        this.txtPeso.setText(null);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * Evento del boton Busca, el evento se hace en CtrlAnimalesRead, ya que
     * necesita conexion con la bd .
     *
     * @param evt
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aniosAnimal;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel estaturaAnimal;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreAnimal;
    private javax.swing.JLabel nombreAtraccionAnimal;
    private javax.swing.JLabel nombrePistaAnimal;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel pesoAnimal;
    private javax.swing.JLabel tipoAnimal;
    private javax.swing.JLabel tituloAnimal;
    public javax.swing.JTextField txtAnios;
    public javax.swing.JTextField txtEstatura;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreAtraccion;
    public javax.swing.JTextField txtNombrePista;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
