package vista;

/**
 * Clase donde podemos consultar los datos de un Artista de la BD.
 *
 * @author IvanSM
 */
public class VentanaDatosArtista extends javax.swing.JFrame {

    /**
     * Creates new form VistaAnimales
     */
    public VentanaDatosArtista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreArtista = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        nif = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        NifJefe = new javax.swing.JLabel();
        txtNifJefe = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        tituloAnimal = new javax.swing.JLabel();
        fondoVentana = new javax.swing.JLabel();

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setOpaque(false);
        panelFormulario.setLayout(new javax.swing.BoxLayout(panelFormulario, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreArtista.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreArtista.setForeground(new java.awt.Color(255, 255, 255));
        nombreArtista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreArtista.setText("Nombre:");
        nombreArtista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombreArtista.setPreferredSize(new java.awt.Dimension(90, 24));
        nombreArtista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, 48));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, 30));

        apellidos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        apellidos.setForeground(new java.awt.Color(255, 255, 255));
        apellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apellidos.setText("Apellidos:");
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 48));

        txtApellidos.setEditable(false);
        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 30));

        nif.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nif.setForeground(new java.awt.Color(255, 255, 255));
        nif.setText("NIF:");
        jPanel1.add(nif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 48));

        txtNif.setForeground(new java.awt.Color(0, 0, 0));
        txtNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifActionPerformed(evt);
            }
        });
        jPanel1.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 30));

        NifJefe.setBackground(new java.awt.Color(255, 255, 255));
        NifJefe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        NifJefe.setForeground(new java.awt.Color(255, 255, 255));
        NifJefe.setText("NIF del Jefe:");
        jPanel1.add(NifJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 329, 48));

        txtNifJefe.setEditable(false);
        txtNifJefe.setBackground(new java.awt.Color(255, 255, 255));
        txtNifJefe.setForeground(new java.awt.Color(0, 0, 0));
        txtNifJefe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNifJefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifJefeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNifJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, 30));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 80, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 80, 40));

        panelFormulario.add(jPanel1);

        tituloAnimal.setBackground(new java.awt.Color(0, 0, 0));
        tituloAnimal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tituloAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tituloAnimal.setText("Insertar animal en la base de datos");

        fondoVentana.setIcon(new javax.swing.ImageIcon("C:\\Users\\IvanSM\\Documents\\NetBeansProjects\\ProjectoCircoIvanSM\\src\\images\\artistas.png")); // NOI18N
        fondoVentana.setPreferredSize(new java.awt.Dimension(3035, 2163));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(842, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifActionPerformed

    /**
     * Evento del boton Atras que cierra la ventana.
     *
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);// Cierra la ventana principal y deja la secundaria
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * Evento del boton Busca, el evento se hace en CtrlArtistaRead, ya que
     * necesita conexion con la bd .
     *
     * @param evt
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Evento del boton limpiar que hace limpiar los campos del formulario.
     *
     * @param evt
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.txtNombre.setText(null);
        this.txtApellidos.setText(null);
        this.txtNif.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNifJefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifJefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifJefeActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NifJefe;
    private javax.swing.JLabel apellidos;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nif;
    private javax.swing.JLabel nombreArtista;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel tituloAnimal;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtNif;
    public javax.swing.JTextField txtNifJefe;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
