package vista;

/**
 * Clase ventana artistas donde se encuentra el formulario para insertar
 * Artistas en la BD
 *
 * @author IvanSM
 */
public class VentanaArtista extends javax.swing.JFrame {

    /**
     * Creates new form VistaAnimales
     */
    public VentanaArtista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nombreArtista = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        nif = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        nombreAtraccionAnimal = new javax.swing.JLabel();
        lisNifJefe = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        tituloAnimal = new javax.swing.JLabel();
        fondoVentana = new javax.swing.JLabel();

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setOpaque(false);
        panelFormulario.setLayout(new javax.swing.BoxLayout(panelFormulario, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreArtista.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreArtista.setForeground(new java.awt.Color(255, 255, 255));
        nombreArtista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreArtista.setText("Nombre:");
        nombreArtista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombreArtista.setPreferredSize(new java.awt.Dimension(90, 24));
        nombreArtista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, 48));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, 30));

        apellidos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        apellidos.setForeground(new java.awt.Color(255, 255, 255));
        apellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apellidos.setText("Apellidos:");
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 48));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 30));

        nif.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nif.setForeground(new java.awt.Color(255, 255, 255));
        nif.setText("NIF:");
        jPanel1.add(nif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 48));

        txtNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifActionPerformed(evt);
            }
        });
        jPanel1.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, 30));

        nombreAtraccionAnimal.setBackground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombreAtraccionAnimal.setForeground(new java.awt.Color(255, 255, 255));
        nombreAtraccionAnimal.setText("NIF del Jefe:");
        jPanel1.add(nombreAtraccionAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 329, 48));

        lisNifJefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "88888888F", "22222222B", " " }));
        jPanel1.add(lisNifJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, 30));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 80, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 100, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 80, 40));

        panelFormulario.add(jPanel1);

        tituloAnimal.setBackground(new java.awt.Color(0, 0, 0));
        tituloAnimal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tituloAnimal.setForeground(new java.awt.Color(255, 255, 255));
        tituloAnimal.setText("Insertar animal en la base de datos");

        fondoVentana.setIcon(new javax.swing.ImageIcon("C:\\Users\\IvanSM\\Documents\\NetBeansProjects\\ProjectoCircoIvanSM\\src\\images\\artistas.png")); // NOI18N
        fondoVentana.setPreferredSize(new java.awt.Dimension(3035, 2163));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(tituloAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(842, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifActionPerformed
    /**
     * Evento del btnAtras que cierra la ventana
     *
     * @param evt
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);// Cierra la ventana principal y deja la secundaria
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Evento del btnLimpiar que limpia los campos del formulario
     *
     * @param evt
     */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.txtNombre.setText(null);
        this.txtApellidos.setText(null);
        this.txtNif.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> lisNifJefe;
    private javax.swing.JLabel nif;
    private javax.swing.JLabel nombreArtista;
    private javax.swing.JLabel nombreAtraccionAnimal;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel tituloAnimal;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtNif;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
