package vista;

/**
 * Clase ventana Acerca de.
 *
 * @author IvanSM
 */
public class VentanaAcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAcercaDe
     */
    public VentanaAcercaDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        lblIconoCirco = new javax.swing.JLabel();
        jlblIvan2 = new javax.swing.JLabel();
        jlblIvan = new javax.swing.JLabel();
        FondoVentanaPerro = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptar.setText("Aceptar");
        aceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, 40));

        lblIconoCirco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIconoCirco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dom.png"))); // NOI18N
        lblIconoCirco.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblIconoCirco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblIconoCirco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        jlblIvan2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblIvan2.setForeground(new java.awt.Color(255, 255, 255));
        jlblIvan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblIvan2.setText("Realizado por:");
        jlblIvan2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblIvan2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlblIvan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 40));

        jlblIvan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlblIvan.setForeground(new java.awt.Color(255, 255, 255));
        jlblIvan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblIvan.setText(" Ivan Salguero Martin");
        jlblIvan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblIvan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlblIvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 170, 20));

        FondoVentanaPerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perro.gif"))); // NOI18N
        jPanel1.add(FondoVentanaPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 340));

        setSize(new java.awt.Dimension(545, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton aceptar que cierra la ventana
     *
     * @param evt
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoVentanaPerro;
    private javax.swing.JButton aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblIvan;
    private javax.swing.JLabel jlblIvan2;
    private javax.swing.JLabel lblIconoCirco;
    // End of variables declaration//GEN-END:variables
}
